! FRR OSPF Config (Generated)
router ospf
 ospf router-id 192.168.20.155
 redistribute static route-map OSPF-EXPORT
 network 192.168.20.0/24 area 0
 network 198.18.0.0/16 area 0
!
route-map OSPF-EXPORT permit 10
 match tag 100
!