#!/bin/bash
# ProxyGW Installation & Deployment Script
# Supports both fresh installs and updates.
# Usage: ./install.sh

set -euo pipefail

REPO_DIR="/root/proxygw"
export GO111MODULE=on

echo "=== ProxyGW Deployment Script ==="

echo "[1/6] Installing system dependencies..."
apt-get update
apt-get install -y build-essential nftables frr sqlite3 curl golang nodejs npm wget unzip

echo "[2/6] Setting up routing rules and system settings..."
# Free port 53 from systemd-resolved
if grep -q "#DNSStubListener=yes" /etc/systemd/resolved.conf || grep -q "DNSStubListener=yes" /etc/systemd/resolved.conf || ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
    echo "Configuring systemd-resolved to free port 53..."
    sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
    sed -i 's/DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
    # Ensure it is set if not found
    if ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
        echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
    fi
    systemctl restart systemd-resolved || true
fi
if ! grep -q "100 tproxy" /etc/iproute2/rt_tables; then
    echo "100 tproxy" >> /etc/iproute2/rt_tables
fi
# Add rule if not exists
ip rule show | grep -q "fwmark 0x1 lookup tproxy" || ip rule add fwmark 1 table tproxy
ip route show table tproxy | grep -q "local default dev lo" || ip route add local default dev lo table tproxy

# Apply system kernel tunings for Transparent Proxying
echo "Applying sysctl kernel tunings for BBR and Conntrack..."
cat << 'SYSCTL_EOF' > /etc/sysctl.d/99-proxygw.conf
# /etc/sysctl.d/99-proxygw.conf
# Auto-generated by ProxyGW Deployment

# --- 1. Routing & Forwarding ---
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# --- 2. Conntrack Optimization ---
net.netfilter.nf_conntrack_max = 1048576
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 120
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 60
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 120

# --- 3. TCP Ports & Concurrency ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 500000
net.core.somaxconn = 8192

# --- 4. Throughput & BBR ---
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_fastopen = 3
SYSCTL_EOF
sysctl --system || true

echo "[3/6] Setting up directory structure..."
mkdir -p "$REPO_DIR/config"
mkdir -p "$REPO_DIR/core/mosdns"
mkdir -p "$REPO_DIR/core/xray"
mkdir -p "$REPO_DIR/core/nftables"
mkdir -p "$REPO_DIR/core/frr"
mkdir -p "$REPO_DIR/systemd"

echo "[4/6] Building backend..."
cd "$REPO_DIR/backend"
if [ ! -f go.mod ]; then
    go mod init proxygw
fi
go mod tidy
go build -o proxygw-backend .

echo "[5/6] Creating Systemd service..."
cp "$REPO_DIR/systemd/proxygw.service" /etc/systemd/system/


echo "[5.5/6] Installing Xray and Mosdns and their Systemd services..."
if [ ! -f "/usr/local/bin/mosdns" ]; then
    wget -qO /tmp/mosdns.zip "https://github.com/IrineSistiana/mosdns/releases/download/v5.3.3/mosdns-linux-amd64.zip"
    unzip -qo /tmp/mosdns.zip mosdns -d /usr/local/bin/
    chmod +x /usr/local/bin/mosdns
fi

if [ ! -f "/usr/local/bin/xray" ]; then
    wget -qO /tmp/xray.zip "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
    unzip -qo /tmp/xray.zip xray -d /usr/local/bin/
    chmod +x /usr/local/bin/xray
fi



cp "$REPO_DIR/systemd/mosdns.service" /etc/systemd/system/
cp "$REPO_DIR/systemd/xray.service" /etc/systemd/system/

echo "[6/6] Starting services..."
systemctl daemon-reload
systemctl enable --now proxygw mosdns xray

# Automatically generate a secure password if it's a fresh install
# Wait a few seconds for the database to be initialized by the backend
sleep 3
if [ -f "$REPO_DIR/config/bootstrap_password.txt" ]; then
    echo "=========================================================="
    echo "ProxyGW is running! A random initial password was generated:"
    cat "$REPO_DIR/config/bootstrap_password.txt"
    echo "Please login at http://$(hostname -I | awk '{print $1}') and CHANGE IT immediately."
    echo "=========================================================="
else
    echo "=========================================================="
    echo "ProxyGW is running at http://$(hostname -I | awk '{print $1}')"
    echo "If this is a fresh install, check the backend logs for the bootstrap password."
    echo "=========================================================="
fi
