#!/bin/bash
# ProxyGW Installation & Deployment Script
# Supports both fresh installs and updates.
# Usage: ./install.sh

set -euo pipefail

echo "=== ProxyGW Deployment Script ==="

# OS and Architecture Check
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "$ID" != "debian" && "$ID" != "ubuntu" ]]; then
        echo "Error: This script is only designed for Debian/Ubuntu based systems."
        exit 1
    fi
else
    echo "Warning: Cannot determine OS. Proceeding anyway..."
fi

ARCH=$(uname -m)
case "$ARCH" in
    x86_64) XRAY_ARCH="64"; MOSDNS_ARCH="amd64" ;;
    aarch64) XRAY_ARCH="arm64-v8a"; MOSDNS_ARCH="arm64" ;;
    *) echo "Error: Unsupported architecture: $ARCH"; exit 1 ;;
esac

REPO_DIR="/root/proxygw"

# Ensure repository exists for frontend and templates
if [ ! -d "$REPO_DIR/.git" ]; then
    echo "[0/6] Cloning ProxyGW repository..."
    apt-get update >/dev/null 2>&1 || true
    apt-get install -y git >/dev/null 2>&1 || true
    git clone https://github.com/zlylong/proxygw.git "$REPO_DIR"
fi

# Switch to repo dir before proceeding
cd "$REPO_DIR"
echo "[1/6] Installing system dependencies..."
apt-get update
apt-get install -y nftables frr curl wget unzip iproute2

echo "[2/6] Setting up routing rules and system settings..."

# Fail-safe DNS: Break systemd-resolved symlink and inject static public DNS
# This prevents the system from losing DNS resolution if installation fails or when port 53 is freed.
echo "Configuring fail-safe DNS..."
chattr -i /etc/resolv.conf 2>/dev/null || true
rm -f /etc/resolv.conf
cat << 'RESOLV_EOF' > /etc/resolv.conf
nameserver 119.29.29.29
nameserver 223.5.5.5
nameserver 1.1.1.1
RESOLV_EOF

# Free port 53 from systemd-resolved
if grep -q "#DNSStubListener=yes" /etc/systemd/resolved.conf || grep -q "DNSStubListener=yes" /etc/systemd/resolved.conf || ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
    echo "Configuring systemd-resolved to free port 53..."
    sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
    sed -i 's/DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
    # Ensure it is set if not found
    if ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
        echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
    fi
    systemctl restart systemd-resolved || true
fi
if ! grep -q "100 tproxy" /etc/iproute2/rt_tables; then
    echo "100 tproxy" >> /etc/iproute2/rt_tables
fi
# Add rule if not exists
ip rule show | grep -q "fwmark 0x1 lookup tproxy" || ip rule add fwmark 1 table tproxy 2>/dev/null || true
ip route show table tproxy | grep -q "local default dev lo" || ip route add local default dev lo table tproxy 2>/dev/null || true

# Apply system kernel tunings for Transparent Proxying
echo "Applying sysctl kernel tunings for BBR and Conntrack..."
cat << 'SYSCTL_EOF' > /etc/sysctl.d/99-proxygw.conf
# /etc/sysctl.d/99-proxygw.conf
# Auto-generated by ProxyGW Deployment

# --- 1. Routing & Forwarding ---
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.route_localnet = 1

# --- 2. Conntrack Optimization ---
net.netfilter.nf_conntrack_max = 1048576
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 120
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 60
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 120

# --- 3. TCP Ports & Concurrency ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 500000
net.core.somaxconn = 32768

# --- 4. Throughput & BBR ---
net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = bbr
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_fastopen = 3
SYSCTL_EOF
sysctl --system || true


echo "[3/6] Setting up directory structure..."
mkdir -p "$REPO_DIR/config"
mkdir -p "$REPO_DIR/core/mosdns"
mkdir -p "$REPO_DIR/core/xray"
mkdir -p "$REPO_DIR/core/nftables"
mkdir -p "$REPO_DIR/core/frr"
mkdir -p "$REPO_DIR/systemd"

echo "[4/6] Downloading backend from GitHub Releases..."
# Try to get version from local git first
if [ -d "$REPO_DIR/.git" ]; then
    PROXYGW_LATEST=$(cd "$REPO_DIR" && git describe --tags --abbrev=0 2>/dev/null || true)
else
    PROXYGW_LATEST=""
fi

# Fallback to GitHub API if git fails
if [ -z "$PROXYGW_LATEST" ]; then
    PROXYGW_LATEST=$(curl --retry 3 --connect-timeout 5 -s -4 https://api.github.com/repos/zlylong/proxygw/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' || true)
fi

# Ultimate fallback if both git and API fail (GFW block / no IPv4)
if [ -z "$PROXYGW_LATEST" ]; then
    echo "Warning: API blocked. Using fallback version v1.4.12..."
    PROXYGW_LATEST="v1.4.12"
fi
if [ "$ARCH" = "x86_64" ]; then
    wget -q -4 -O "$REPO_DIR/backend/proxygw-backend" "https://github.com/zlylong/proxygw/releases/download/${PROXYGW_LATEST}/proxygw-backend-linux-amd64"
elif [ "$ARCH" = "aarch64" ]; then
    wget -q -4 -O "$REPO_DIR/backend/proxygw-backend" "https://github.com/zlylong/proxygw/releases/download/${PROXYGW_LATEST}/proxygw-backend-linux-arm64"
fi
chmod +x "$REPO_DIR/backend/proxygw-backend"


echo "[5/6] Creating Systemd services..."
cat << 'SYS_EOF' > /etc/systemd/system/proxygw.service
[Unit]
Description=ProxyGW Backend Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/backend
ExecStart=/root/proxygw/backend/proxygw-backend
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

# Security Sandboxing
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
ReadWritePaths=-/root/proxygw -/usr/local/bin -/etc/frr

[Install]
WantedBy=multi-user.target
SYS_EOF

cat << 'SYS_EOF' > /etc/systemd/system/mosdns.service
[Unit]
Description=Mosdns Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/core/mosdns
ExecStart=/root/proxygw/core/mosdns/mosdns start -d /root/proxygw/core/mosdns
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
SYS_EOF

cat << 'SYS_EOF' > /etc/systemd/system/xray.service
[Unit]
Description=Xray Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/core/xray
Environment=XRAY_LOCATION_ASSET=/root/proxygw/core/mosdns
ExecStart=/root/proxygw/core/xray/xray run -confdir /root/proxygw/core/xray
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
SYS_EOF


echo "[5.5/6] Verifying and Installing Core Binaries ($ARCH)..."
# Check and download Xray if it doesn't match the architecture or doesn't exist
if ! "$REPO_DIR/core/xray/xray" version >/dev/null 2>&1; then
    echo "Downloading Xray for $ARCH..."
    XRAY_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-${XRAY_ARCH}.zip"
    wget -q -4 -O /tmp/xray.zip "$XRAY_URL"
    unzip -qo /tmp/xray.zip xray -d "$REPO_DIR/core/xray/"
    rm -f /tmp/xray.zip
fi
chmod +x "$REPO_DIR/core/xray/xray" || true

# Check and download Mosdns if it doesn't match the architecture or doesn't exist
if ! "$REPO_DIR/core/mosdns/mosdns" version >/dev/null 2>&1; then
    echo "Downloading Mosdns for $ARCH..."
    MOSDNS_LATEST=$(curl -s -4 https://api.github.com/repos/IrineSistiana/mosdns/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    if [ -n "$MOSDNS_LATEST" ]; then
        MOSDNS_URL="https://github.com/IrineSistiana/mosdns/releases/download/${MOSDNS_LATEST}/mosdns-linux-${MOSDNS_ARCH}.zip"
        wget -q -4 -O /tmp/mosdns.zip "$MOSDNS_URL"
        unzip -qo /tmp/mosdns.zip mosdns -d "$REPO_DIR/core/mosdns/"
        rm -f /tmp/mosdns.zip
    else
        echo "Warning: Failed to fetch Mosdns latest version!"
    fi
fi
chmod +x "$REPO_DIR/core/mosdns/mosdns" || true



echo "Applying strict anti-loop Nftables rules..."
cat << 'NFT_EOF' > /etc/nftables.conf
#!/usr/sbin/nft -f
flush ruleset
table inet proxygw {
    chain prerouting {
        type filter hook prerouting priority mangle; policy accept;
        # Xray local output MUST bypass TProxy to prevent loop
        meta mark 0x02 return
        # Ignore LAN / Multicast / Broadcast traffic
        ip daddr { 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 224.0.0.0/4, 255.255.255.255/32 } return
        # Drop IPv6 traffic to prevent un-proxied leak when DNS resolves AAAA
        meta nfproto ipv6 drop
        # TProxy all remaining IPv4 traffic
        meta l4proto { tcp, udp } mark set 1 tproxy ip to 127.0.0.1:12345 accept
    }
    chain output {
        type route hook output priority mangle; policy accept;
        # Xray local output MUST bypass TProxy to prevent loop
        meta mark 0x02 return
        # Ignore LAN / Multicast / Broadcast traffic
        ip daddr { 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 224.0.0.0/4, 255.255.255.255/32 } return
        # TProxy tag for localhost proxy
        meta l4proto { tcp, udp } mark set 1 accept
    }
}
NFT_EOF
systemctl enable nftables
nft -f /etc/nftables.conf || true

echo "[6/6] Starting services..."
systemctl daemon-reload
systemctl enable proxygw mosdns xray || true

# Force restart if already running to pick up updates and generate bootstrap if needed
systemctl restart proxygw mosdns xray || true

# Automatically generate a secure password if it's a fresh install
# Wait for the database and bootstrap password to be initialized by the backend
echo "Waiting for ProxyGW to initialize..."
for i in {1..15}; do
    if [ -f "/config/bootstrap_password.txt" ]; then
        break
    fi
    sleep 1
done

if [ -f "$REPO_DIR/config/bootstrap_password.txt" ]; then
    echo "=========================================================="
    echo "ProxyGW is running! A random initial password was generated:"
    cat "$REPO_DIR/config/bootstrap_password.txt"
    echo "Please login at http://$(hostname -I | awk '{print $1}') and CHANGE IT immediately."
    echo "=========================================================="
else
    echo "=========================================================="
    echo "ProxyGW is running at http://$(hostname -I | awk '{print $1}')"
    echo "If this is a fresh install, check the backend logs for the bootstrap password."
    echo "=========================================================="
fi
